spring:
  datasource:
    password: root
    username: 
    url: 'jdbc:mysql://localhost:3306/fornecedor'
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
